version: '3.9'

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5163:5163
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=db
      - DB_NAME=prac-hris
      - DB_PASSWORD=P@ssw0rd
    volumes:
      - ./backend:/src
    networks:
      - prac-hris
    depends_on:
      - db
  db:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    ports:
      - '1433:1433'
    restart: always
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=P@ssw0rd
    networks:
      - prac-hris
networks:
  prac-hris:
    driver: bridge
