version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - 5163:5163
    env_file:
      - .env.backend
    volumes:
      - ./backend:/src
    networks:
      - prac-hris
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    env_file:
      - .env.frontend
    networks:
      - prac-hris
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
  db:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    user: root
    ports:
      - '1433:1433'
    restart: always
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=P@ssw0rd
    networks:
      - prac-hris
networks:
  prac-hris:
    driver: bridge
