version: '3.9'

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5163:5163
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./backend:/app
    networks:
      - prac-hris
  # sql:
  #   image: 'mcr.microsoft.com/mssql/server:2022-latest'
  #   container_name: sql_server2022
  #   ports: # not actually needed, because the two services are on the same network
  #     - '1433:1433'
  #   volumes:
  #     - ./data:/var/opt/mssql/data
  #     - ./log:/var/opt/mssql/log
  #     - ./secrets:/var/opt/mssql/secrets
  #   environment:
  #     - ACCEPT_EULA=y
  #     - SA_PASSWORD=A&VeryComplex123Password
  #   networks:
  #     - prac-hris
networks:
  prac-hris:
    driver: bridge
